import { createSlice } from "@reduxjs/toolkit";

const initialState = [
    { id: 1, title: "The Alchemist" },
    { id: 2, title: "To Kill a Mockingbird" },
    { id: 3, title: "1984" },
    { id: 4, title: "Pride and Prejudice" },
    { id: 5, title: "The Great Gatsby" },
    { id: 6, title: "The Catcher in the Rye" },
    { id: 7, title: "The Lord of the Rings" },
    { id: 8, title: "Harry Potter and the Sorcerer's Stone" },
    { id: 9, title: "The Hunger Games" },
    { id: 10, title: "Game of Thrones" },
    { id: 11, title: "Dune" },
    { id: 12, title: "The Hobbit" },
    { id: 13, title: "The Da Vinci Code" },
    { id: 14, title: "The Girl with the Dragon Tattoo" },
    { id: 15, title: "The Shining" },
    { id: 16, title: "Brave New World" },
    { id: 17, title: "The Hitchhiker's Guide to the Galaxy" },
    { id: 18, title: "The Road" },
    { id: 19, title: "Fahrenheit 451" },
    { id: 20, title: "The Stand" },
    { id: 21, title: "Moby-Dick" },
    { id: 22, title: "The Chronicles of Narnia" },
    { id: 23, title: "A Song of Ice and Fire" },
    { id: 24, title: "The Grapes of Wrath" },
    { id: 25, title: "The Kite Runner" },
    { id: 26, title: "The Girl on the Train" },
    { id: 27, title: "Gone Girl" },
    { id: 28, title: "The Road Less Traveled" },
    { id: 29, title: "The Help" },
    { id: 30, title: "The Fault in Our Stars" },
    { id: 31, title: "The Silent Patient" },
    { id: 32, title: "The Secret Garden" },
    { id: 33, title: "The Color Purple" },
    { id: 34, title: "The Sun Also Rises" },
    { id: 35, title: "The Picture of Dorian Gray" },
    { id: 36, title: "The Wind in the Willows" },
    { id: 37, title: "The Little Prince" },
    { id: 38, title: "The Jungle Book" },
    { id: 39, title: "The Glass Castle" },
    { id: 40, title: "The Outsiders" },
    { id: 41, title: "The Stand" },
    { id: 42, title: "The Road" },
    { id: 43, title: "The Brothers Karamazov" },
    { id: 44, title: "The Count of Monte Cristo" },
    { id: 45, title: "The Name of the Wind" },
    { id: 46, title: "The Giver" },
    { id: 47, title: "The Martian" },
    { id: 48, title: "The Book Thief" },
    { id: 49, title: "The Goldfinch" },
    { id: 50, title: "The Night Circus" },
    { id: 51, title: "The Help" },
    { id: 52, title: "The Fault in Our Stars" },
    { id: 53, title: "The Silent Patient" },
    { id: 54, title: "The Secret Garden" },
    { id: 55, title: "The Color Purple" },
    { id: 56, title: "The Sun Also Rises" },
    { id: 57, title: "The Picture of Dorian Gray" },
    { id: 58, title: "The Wind in the Willows" },
    { id: 59, title: "The Little Prince" },
    { id: 60, title: "The Jungle Book" },
    { id: 61, title: "The Glass Castle" },
    { id: 62, title: "The Outsiders" },
    { id: 63, title: "The Stand" },
    { id: 64, title: "The Road" },
    { id: 65, title: "The Brothers Karamazov" },
    { id: 66, title: "The Count of Monte Cristo" },
    { id: 67, title: "The Name of the Wind" },
    { id: 68, title: "The Giver" },
    { id: 69, title: "The Martian" },
    { id: 70, title: "The Book Thief" },
    { id: 71, title: "The Goldfinch" },
    { id: 72, title: "The Night Circus" },
    { id: 73, title: "The Help" },
    { id: 74, title: "The Fault in Our Stars" },
    { id: 75, title: "The Silent Patient" },
    { id: 76, title: "The Secret Garden" },
    { id: 77, title: "The Color Purple" },
    { id: 78, title: "The Sun Also Rises" },
    { id: 79, title: "The Picture of Dorian Gray" },
    { id: 80, title: "The Wind in the Willows" },
    { id: 81, title: "The Little Prince" },
    { id: 82, title: "The Jungle Book" },
    { id: 83, title: "The Glass Castle" },
    { id: 84, title: "The Outsiders" },
    { id: 85, title: "The Stand" },
    { id: 86, title: "The Road" },
    { id: 87, title: "The Brothers Karamazov" },
    { id: 88, title: "The Count of Monte Cristo" },
    { id: 89, title: "The Name of the Wind" },
    { id: 90, title: "The Giver" },
    { id: 91, title: "The Martian" },
    { id: 92, title: "The Book Thief" },
    { id: 93, title: "The Goldfinch" },
    { id: 94, title: "The Night Circus" },
    { id: 95, title: "The Help" },
    { id: 96, title: "The Fault in Our Stars" },
    { id: 97, title: "The Silent Patient" },
    { id: 98, title: "The Secret Garden" },
    { id: 99, title: "The Color Purple" },
    { id: 100, title: "The Sun Also Rises" }
]


const ordersSlice = createSlice({
    name: "orders",
    initialState,
    reducers: {}
})

export default ordersSlice.reducer;