import { createSlice } from "@reduxjs/toolkit";

const initialState = [
    { id: 1, title: "The Alchemist", status: "Printing" },
    { id: 2, title: "To Kill a Mockingbird", status: "Canceled" },
    { id: 3, title: "1984", status: "Ready" },
    { id: 4, title: "Pride and Prejudice", status: "Paused" },
    { id: 5, title: "The Great Gatsby", status: "Queued" },
    { id: 6, title: "The Catcher in the Rye", status: "Printing" },
    { id: 7, title: "The Lord of the Rings", status: "Paused" },
    { id: 8, title: "Harry Potter and the Sorcerer's Stone", status: "Ready" },
    { id: 9, title: "The Hunger Games", status: "Queued" },
    { id: 10, title: "Game of Thrones", status: "Canceled" },
    { id: 11, title: "Dune", status: "Paused" },
    { id: 12, title: "The Hobbit", status: "Printing" },
    { id: 13, title: "The Da Vinci Code", status: "Ready" },
    { id: 14, title: "The Girl with the Dragon Tattoo", status: "Queued" },
    { id: 15, title: "The Shining", status: "Printing" },
    { id: 16, title: "Brave New World", status: "Paused" },
    { id: 17, title: "The Hitchhiker's Guide to the Galaxy", status: "Canceled" },
    { id: 18, title: "The Road", status: "Queued" },
    { id: 19, title: "Fahrenheit 451", status: "Printing" },
    { id: 20, title: "The Stand", status: "Ready" },
    { id: 21, title: "Moby-Dick", status: "Paused" },
    { id: 22, title: "The Chronicles of Narnia", status: "Printing" },
    { id: 23, title: "A Song of Ice and Fire", status: "Queued" },
    { id: 24, title: "The Grapes of Wrath", status: "Canceled" },
    { id: 25, title: "The Kite Runner", status: "Printing" },
    { id: 26, title: "The Girl on the Train", status: "Paused" },
    { id: 27, title: "Gone Girl", status: "Queued" },
    { id: 28, title: "The Road Less Traveled", status: "Printing" },
    { id: 29, title: "The Help", status: "Ready" },
    { id: 30, title: "The Fault in Our Stars", status: "Queued" },
    { id: 31, title: "The Silent Patient", status: "Printing" },
    { id: 32, title: "The Secret Garden", status: "Paused" },
    { id: 33, title: "The Color Purple", status: "Ready" },
    { id: 34, title: "The Sun Also Rises", status: "Queued" },
    { id: 35, title: "The Picture of Dorian Gray", status: "Canceled" },
    { id: 36, title: "The Wind in the Willows", status: "Printing" },
    { id: 37, title: "The Little Prince", status: "Paused" },
    { id: 38, title: "The Jungle Book", status: "Ready" },
    { id: 39, title: "The Glass Castle", status: "Queued" },
    { id: 40, title: "The Outsiders", status: "Printing" },
    { id: 41, title: "The Stand", status: "Ready" },
    { id: 42, title: "The Road", status: "Queued" },
    { id: 43, title: "The Brothers Karamazov", status: "Canceled" },
    { id: 44, title: "The Count of Monte Cristo", status: "Printing" },
    { id: 45, title: "The Name of the Wind", status: "Paused" },
    { id: 46, title: "The Giver", status: "Ready" },
    { id: 47, title: "The Martian", status: "Queued" },
    { id: 48, title: "The Book Thief", status: "Printing" },
    { id: 49, title: "The Goldfinch", status: "Paused" },
    { id: 50, title: "The Night Circus", status: "Ready" },
    { id: 51, title: "The Help", status: "Queued" },
    { id: 52, title: "The Fault in Our Stars", status: "Canceled" },
    { id: 53, title: "The Silent Patient", status: "Printing" },
    { id: 54, title: "The Secret Garden", status: "Paused" },
    { id: 55, title: "The Color Purple", status: "Ready" },
    { id: 56, title: "The Sun Also Rises", status: "Queued" },
    { id: 57, title: "The Picture of Dorian Gray", status: "Canceled" },
    { id: 58, title: "The Wind in the Willows", status: "Printing" },
    { id: 59, title: "The Little Prince", status: "Paused" },
    { id: 60, title: "The Jungle Book", status: "Ready" },
    { id: 61, title: "The Glass Castle", status: "Queued" },
    { id: 62, title: "The Outsiders", status: "Printing" },
    { id: 63, title: "The Stand", status: "Ready" },
    { id: 64, title: "The Road", status: "Queued" },
    { id: 65, title: "The Brothers Karamazov", status: "Canceled" },
    { id: 66, title: "The Count of Monte Cristo", status: "Printing" },
    { id: 67, title: "The Name of the Wind", status: "Paused" },
    { id: 68, title: "The Giver", status: "Ready" },
    { id: 69, title: "The Martian", status: "Queued" },
    { id: 70, title: "The Book Thief", status: "Printing" },
    { id: 71, title: "The Goldfinch", status: "Paused" },
    { id: 72, title: "The Night Circus", status: "Ready" },
    { id: 73, title: "The Help", status: "Queued" },
    { id: 74, title: "The Fault in Our Stars", status: "Canceled" },
    { id: 75, title: "The Silent Patient", status: "Printing" },
    { id: 76, title: "The Secret Garden", status: "Paused" },
    { id: 77, title: "The Color Purple", status: "Ready" },
    { id: 78, title: "The Sun Also Rises", status: "Queued" },
    { id: 79, title: "The Picture of Dorian Gray", status: "Canceled" },
    { id: 80, title: "The Wind in the Willows", status: "Printing" },
    { id: 81, title: "The Little Prince", status: "Paused" },
    { id: 82, title: "The Jungle Book", status: "Ready" },
    { id: 83, title: "The Glass Castle", status: "Queued" },
    { id: 84, title: "The Outsiders", status: "Printing" },
    { id: 85, title: "The Stand", status: "Ready" },
    { id: 86, title: "The Road", status: "Queued" },
    { id: 87, title: "The Brothers Karamazov", status: "Canceled" },
    { id: 88, title: "The Count of Monte Cristo", status: "Printing" },
    { id: 89, title: "The Name of the Wind", status: "Paused" },
    { id: 90, title: "The Giver", status: "Ready" },
    { id: 91, title: "The Martian", status: "Queued" },
    { id: 92, title: "The Book Thief", status: "Printing" },
    { id: 93, title: "The Goldfinch", status: "Paused" },
    { id: 94, title: "The Night Circus", status: "Ready" },
    { id: 95, title: "The Help", status: "Queued" },
    { id: 96, title: "The Fault in Our Stars", status: "Canceled" },
    { id: 97, title: "The Silent Patient", status: "Printing" },
    { id: 98, title: "The Secret Garden", status: "Paused" },
    { id: 99, title: "The Color Purple", status: "Ready" },
    { id: 100, title: "The Sun Also Rises", status: "Queued" }
]


const ordersSlice = createSlice({
    name: "orders",
    initialState,
    reducers: {}
})

export default ordersSlice.reducer;